### ISSUE TITLE
Add in page editor

### ISSUE THREAD

**Issue by SheepFromHeaven** [SheepFromHeaven/shader-playground#3]
Add in page editor to make it possible to code shader online

**Comment by SheepFromHeaven** [comment]
@Narigo DO IT!

**Comment by Narigo** [comment]
Ok.

**Comment by Narigo** [comment]
https://github.com/SheepFromHeaven/shader-playground/pull/4

**Comment by Narigo** [comment]
@SheepFromHeaven ping! Add GitHub pages.

**Comment by Narigo** [comment]
Thanks for merging - a nice addition would be to go to settings and enable GitHub pages as well - then we could live code on sheepfromheaven.github.io/shader-playground without even `git clone`! :)

**Comment by SheepFromHeaven** [comment]
@Narigo done 🎉 🎈
